# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/game/server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/game/server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/game/server/CMakeFiles /data/game/server/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/game/server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named debugserver

# Build rule for target.
debugserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debugserver
.PHONY : debugserver

# fast build rule for target.
debugserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/build
.PHONY : debugserver/fast

#=============================================================================
# Target rules for targets named gameserver

# Build rule for target.
gameserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gameserver
.PHONY : gameserver

# fast build rule for target.
gameserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/build
.PHONY : gameserver/fast

#=============================================================================
# Target rules for targets named controlserver

# Build rule for target.
controlserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 controlserver
.PHONY : controlserver

# fast build rule for target.
controlserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/build
.PHONY : controlserver/fast

#=============================================================================
# Target rules for targets named gateserver

# Build rule for target.
gateserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gateserver
.PHONY : gateserver

# fast build rule for target.
gateserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/build
.PHONY : gateserver/fast

controlserver.o: controlserver.cpp.o

.PHONY : controlserver.o

# target to build an object file
controlserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/controlserver.cpp.o
.PHONY : controlserver.cpp.o

controlserver.i: controlserver.cpp.i

.PHONY : controlserver.i

# target to preprocess a source file
controlserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/controlserver.cpp.i
.PHONY : controlserver.cpp.i

controlserver.s: controlserver.cpp.s

.PHONY : controlserver.s

# target to generate assembly for a file
controlserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/controlserver.cpp.s
.PHONY : controlserver.cpp.s

debugserver.o: debugserver.cpp.o

.PHONY : debugserver.o

# target to build an object file
debugserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/debugserver.cpp.o
.PHONY : debugserver.cpp.o

debugserver.i: debugserver.cpp.i

.PHONY : debugserver.i

# target to preprocess a source file
debugserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/debugserver.cpp.i
.PHONY : debugserver.cpp.i

debugserver.s: debugserver.cpp.s

.PHONY : debugserver.s

# target to generate assembly for a file
debugserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/debugserver.cpp.s
.PHONY : debugserver.cpp.s

gameserver.o: gameserver.cpp.o

.PHONY : gameserver.o

# target to build an object file
gameserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/gameserver.cpp.o
.PHONY : gameserver.cpp.o

gameserver.i: gameserver.cpp.i

.PHONY : gameserver.i

# target to preprocess a source file
gameserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/gameserver.cpp.i
.PHONY : gameserver.cpp.i

gameserver.s: gameserver.cpp.s

.PHONY : gameserver.s

# target to generate assembly for a file
gameserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/gameserver.cpp.s
.PHONY : gameserver.cpp.s

gateserver.o: gateserver.cpp.o

.PHONY : gateserver.o

# target to build an object file
gateserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/gateserver.cpp.o
.PHONY : gateserver.cpp.o

gateserver.i: gateserver.cpp.i

.PHONY : gateserver.i

# target to preprocess a source file
gateserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/gateserver.cpp.i
.PHONY : gateserver.cpp.i

gateserver.s: gateserver.cpp.s

.PHONY : gateserver.s

# target to generate assembly for a file
gateserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/gateserver.cpp.s
.PHONY : gateserver.cpp.s

mysocket.o: mysocket.cc.o

.PHONY : mysocket.o

# target to build an object file
mysocket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/mysocket.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/mysocket.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/mysocket.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/mysocket.cc.o
.PHONY : mysocket.cc.o

mysocket.i: mysocket.cc.i

.PHONY : mysocket.i

# target to preprocess a source file
mysocket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/mysocket.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/mysocket.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/mysocket.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/mysocket.cc.i
.PHONY : mysocket.cc.i

mysocket.s: mysocket.cc.s

.PHONY : mysocket.s

# target to generate assembly for a file
mysocket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/mysocket.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/mysocket.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/mysocket.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/mysocket.cc.s
.PHONY : mysocket.cc.s

proto/project.pb.o: proto/project.pb.cc.o

.PHONY : proto/project.pb.o

# target to build an object file
proto/project.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/proto/project.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/proto/project.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/proto/project.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/proto/project.pb.cc.o
.PHONY : proto/project.pb.cc.o

proto/project.pb.i: proto/project.pb.cc.i

.PHONY : proto/project.pb.i

# target to preprocess a source file
proto/project.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/proto/project.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/proto/project.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/proto/project.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/proto/project.pb.cc.i
.PHONY : proto/project.pb.cc.i

proto/project.pb.s: proto/project.pb.cc.s

.PHONY : proto/project.pb.s

# target to generate assembly for a file
proto/project.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/proto/project.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/proto/project.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/proto/project.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/proto/project.pb.cc.s
.PHONY : proto/project.pb.cc.s

proto/server.pb.o: proto/server.pb.cc.o

.PHONY : proto/server.pb.o

# target to build an object file
proto/server.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/proto/server.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/proto/server.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/proto/server.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/proto/server.pb.cc.o
.PHONY : proto/server.pb.cc.o

proto/server.pb.i: proto/server.pb.cc.i

.PHONY : proto/server.pb.i

# target to preprocess a source file
proto/server.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/proto/server.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/proto/server.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/proto/server.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/proto/server.pb.cc.i
.PHONY : proto/server.pb.cc.i

proto/server.pb.s: proto/server.pb.cc.s

.PHONY : proto/server.pb.s

# target to generate assembly for a file
proto/server.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/proto/server.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/proto/server.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/proto/server.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/proto/server.pb.cc.s
.PHONY : proto/server.pb.cc.s

serverbase.o: serverbase.cc.o

.PHONY : serverbase.o

# target to build an object file
serverbase.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/serverbase.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/serverbase.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/serverbase.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/serverbase.cc.o
.PHONY : serverbase.cc.o

serverbase.i: serverbase.cc.i

.PHONY : serverbase.i

# target to preprocess a source file
serverbase.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/serverbase.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/serverbase.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/serverbase.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/serverbase.cc.i
.PHONY : serverbase.cc.i

serverbase.s: serverbase.cc.s

.PHONY : serverbase.s

# target to generate assembly for a file
serverbase.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/serverbase.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/serverbase.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/serverbase.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/serverbase.cc.s
.PHONY : serverbase.cc.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.s
.PHONY : test.cpp.s

tool/circularbuffer.o: tool/circularbuffer.cc.o

.PHONY : tool/circularbuffer.o

# target to build an object file
tool/circularbuffer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/tool/circularbuffer.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/tool/circularbuffer.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/tool/circularbuffer.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/tool/circularbuffer.cc.o
.PHONY : tool/circularbuffer.cc.o

tool/circularbuffer.i: tool/circularbuffer.cc.i

.PHONY : tool/circularbuffer.i

# target to preprocess a source file
tool/circularbuffer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/tool/circularbuffer.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/tool/circularbuffer.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/tool/circularbuffer.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/tool/circularbuffer.cc.i
.PHONY : tool/circularbuffer.cc.i

tool/circularbuffer.s: tool/circularbuffer.cc.s

.PHONY : tool/circularbuffer.s

# target to generate assembly for a file
tool/circularbuffer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/tool/circularbuffer.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/tool/circularbuffer.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/tool/circularbuffer.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/tool/circularbuffer.cc.s
.PHONY : tool/circularbuffer.cc.s

tool/pbhelper.o: tool/pbhelper.cc.o

.PHONY : tool/pbhelper.o

# target to build an object file
tool/pbhelper.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/tool/pbhelper.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/tool/pbhelper.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/tool/pbhelper.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/tool/pbhelper.cc.o
.PHONY : tool/pbhelper.cc.o

tool/pbhelper.i: tool/pbhelper.cc.i

.PHONY : tool/pbhelper.i

# target to preprocess a source file
tool/pbhelper.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/tool/pbhelper.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/tool/pbhelper.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/tool/pbhelper.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/tool/pbhelper.cc.i
.PHONY : tool/pbhelper.cc.i

tool/pbhelper.s: tool/pbhelper.cc.s

.PHONY : tool/pbhelper.s

# target to generate assembly for a file
tool/pbhelper.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debugserver.dir/build.make CMakeFiles/debugserver.dir/tool/pbhelper.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameserver.dir/build.make CMakeFiles/gameserver.dir/tool/pbhelper.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/controlserver.dir/build.make CMakeFiles/controlserver.dir/tool/pbhelper.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateserver.dir/build.make CMakeFiles/gateserver.dir/tool/pbhelper.cc.s
.PHONY : tool/pbhelper.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... controlserver"
	@echo "... debugserver"
	@echo "... gameserver"
	@echo "... gateserver"
	@echo "... test"
	@echo "... controlserver.o"
	@echo "... controlserver.i"
	@echo "... controlserver.s"
	@echo "... debugserver.o"
	@echo "... debugserver.i"
	@echo "... debugserver.s"
	@echo "... gameserver.o"
	@echo "... gameserver.i"
	@echo "... gameserver.s"
	@echo "... gateserver.o"
	@echo "... gateserver.i"
	@echo "... gateserver.s"
	@echo "... mysocket.o"
	@echo "... mysocket.i"
	@echo "... mysocket.s"
	@echo "... proto/project.pb.o"
	@echo "... proto/project.pb.i"
	@echo "... proto/project.pb.s"
	@echo "... proto/server.pb.o"
	@echo "... proto/server.pb.i"
	@echo "... proto/server.pb.s"
	@echo "... serverbase.o"
	@echo "... serverbase.i"
	@echo "... serverbase.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... tool/circularbuffer.o"
	@echo "... tool/circularbuffer.i"
	@echo "... tool/circularbuffer.s"
	@echo "... tool/pbhelper.o"
	@echo "... tool/pbhelper.i"
	@echo "... tool/pbhelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

